version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mymtl_production
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  web:
    env_file:
      - .env
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # local SSL
    command: bundle exec rails s -b "ssl://0.0.0.0:3000?key=/etc/ssl/private/localhost.key&cert=/etc/ssl/certs/localhost.crt"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/public/assets
      - /usr/src/app/public/packs
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://user:password@db/myapp_production
      RAILS_LOG_TO_STDOUT: true
    depends_on:
      - db
volumes:
  pgdata:
