apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "yourdbname"
            - name: POSTGRES_USER
              value: "yourdbuser"
            - name: POSTGRES_PASSWORD
              value: "yourdbpassword"
          ports:
            - containerPort: 5432
